name: "Lucas Neves Pereira"
picture: "src/templates/assets/img/picture.jpg"
bio: "Software Engineer, Content Creator and Open Source Enthusiast."
meta:
  lang: "en"
  description: "Lucas Neves Pereira's personal website"
  title: "Lucas Neves Pereira"
  author: "Lucas Neves Pereira"
  siteUrl: "https://lucasnevespereira.github.io"
links:
  - name: "Github"
    url: "https://github.com/lucasnevespereira"
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/lucasnevespereira/"
  - name: "Youtube"
    url: "https://www.youtube.com/c/lucaasnp"
  - name: "Twitter"
    url: "https://twitter.com/lucaasnp_"
  - name: "Blog"
    url: "https://dev.to/lucasnevespereira"
contact:
  email: "lnevespereira@proton.me"
  phone: ""
  socials:
    - name: "Github"
      url: "https://github.com/lucasnevespereira"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/lucasnevespereira/"
    - name: "Youtube"
      url: "https://www.youtube.com/c/lucaasnp"
    - name: "Twitter"
      url: "https://twitter.com/lucaasnp_"
      
  