title: "Lucas Neves Pereira"
description: "Lucas Neves Pereira's personal website"
lang: "en"
socials:
  - name: "github"
    url: "https://github.com/lucasnevespereira"
  - name: "linkedin"
    url: "https://www.linkedin.com/in/lucasnevespereira/"
  - name: "youtube"
    url: "https://www.youtube.com/c/lucaasnp"